name: update package version and trigger publish

on:
  workflow_dispatch:

permissions: write-all

env:
  npm_org: \@utilslib

jobs:
  pushVersionCode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git pull --rebase
          git config user.name 'IBIN'
          git config user.email 'ibin@qq.com'

      - uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Upgrade
        run: |
          npm version patch

      - run: |
          npm i -g pnpm@8
          pnpm i
          pnpm build

      - name: push
        run: |
          git push

  trigger:
    runs-on: ubuntu-latest
    needs: pushVersionCode
    steps:
      - name: Trigger publish workflow
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/publish.yml/dispatches \
          -d '{"ref":"${{github.ref_name}}"}'
